version: "3.8"  # Specify the docker-compose version

services:
  web:  # Give your service a name (e.g., "web")
    build:
      context: .  # Use the current directory as the build context
      dockerfile: Dockerfile  # Specify the name of your Dockerfile
    ports:
      - "8000:8000"  # Map port 8000 on the host to port 8000 in the container